apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata: 
      labels: 
        app: kafka-producer
    spec:
      imagePullPolicy: Always
      containers:
      - image: quay.io/darlowsk/kafka-producer:test5
        name: kafka-producer
        resources: {}
        env:
          - name: PORT
            value: "9093"
          - name: BOOTSTRAP
            value: "my-cluster-kafka-bootstrap"
          - name: CA
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: CERT
            valueFrom:
              secretKeyRef:
                name: my-producer
                key: user.crt
          - name: KEY
            valueFrom:
              secretKeyRef:
                name: my-producer
                key: user.key
          - name: PYTHONUNBUFFERED
            value: "1"