apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata: 
      labels: 
        app: kafka-producer
    spec:
      imagePullPolicy: Always
      containers:
      - image: quay.io/darlowsk/kafka-producer:latest
        name: kafka-producer
        resources: {}
        env:
          - name: PORT
            value: "9092"
          - name: BOOTSTRAP
            value: "my-cluster-kafka-bootstrap"